name: Save output.csv to repo

on:
  push:
    branches: [main]  # or your branch name
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run main.py
        run: python main.py

      - name: Upload output.csv
        uses: actions/upload-artifact@v4
        with:
          name: output-file
          path: Output/output.csv
