name: Save output.csv to repo

on:
  push:
    branches: [main]

jobs:
  save-output:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Important: allows custom git commands

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python script
        run: python main.py

      - name: Commit and push output.csv
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Output/output.csv
          git commit -m "Add generated output.csv"
          git push origin main
