name: Save output.csv to repo

on:
  push:
    branches: [main]  # or your branch name
  workflow_dispatch:

jobs:
  save-output:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # ✅ enables pushing with GITHUB_TOKEN

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python script
        run: python main.py

      - name: Commit and push output.csv
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add Output/output.csv

          # Only commit if the file changed
          git diff --cached --quiet || git commit -m "Update output.csv [skip ci]"
          git push
